#include <iostream>
#include <windows.h>
using namespace std;
main()
{
system("color 20");
cout<<"                                                "<<endl;
cout<<"                       AA                       "<<endl;
cout<<"                      AAAA                      "<<endl;
cout<<"                     A  AAA                     "<<endl;
cout<<"                    A    AAA                    "<<endl;
cout<<"                   A      AAA                   "<<endl;
cout<<"                  AAAAAAAAAAAA                  "<<endl;
cout<<"                 A          AAA                 "<<endl;
cout<<"                A            AAA                "<<endl;
cout<<"              AAA            AAAAA             "<<endl;
cout<<"                                            "<<endl;
cout<<"                                            "<<endl;
cout<<"             XXXXXX     XXXXX                   "<<endl;
cout<<"               XXX       X                      "<<endl;
cout<<"                XXX     X                       "<<endl;
cout<<"                 XXX   X                        "<<endl;
cout<<"                  XXX X                         "<<endl;
cout<<"                   XXX                          "<<endl;
cout<<"                    XXX                         "<<endl;
cout<<"                   X XXX                        "<<endl;
cout<<"                  X   XXX                       "<<endl;
cout<<"                 X     XXX                      "<<endl;
cout<<"                X       XXX                     "<<endl;
cout<<"             XXXXX     XXXXXX                   "<<endl;
cout<<"                                            "<<endl;
cout<<"                                            "<<endl;
cout<<"                                            "<<endl;
cout<<"               ZZZZZZZZZZZZZ                  "<<endl;
cout<<"               Z        ZZZ                   "<<endl;
cout<<"                      ZZZ                     "<<endl;
cout<<"                    ZZZ                       "<<endl;
cout<<"                  ZZZ                         "<<endl;
cout<<"                ZZZ        Z                  "<<endl;
cout<<"               ZZZZZZZZZZZZZ                  "<<endl;
cout<<"                                            "<<endl;
cout<<"                                            "<<endl;
cout<<"               KKK     KKK                      "<<endl;
cout<<"               KKK    K                         "<<endl;
cout<<"               KKK  K                           "<<endl;
cout<<"               KKKK                             "<<endl;
cout<<"               KKKK                             "<<endl;
cout<<"               KKKKK                            "<<endl;
cout<<"               KKK KKK                          "<<endl;
cout<<"               KKK   KKK                        "<<endl;
cout<<"               KKK    KKKK                      "<<endl;
cout<<"                                            "<<endl;
cout<<"                                            "<<endl;
cout<<"                   SSSSSS                         "<<endl;
cout<<"                SSSS     SSS                      "<<endl;
cout<<"                SSSSS      S                      "<<endl;
cout<<"                  SSSSS                           "<<endl;
cout<<"                     SSSSS                        "<<endl;
cout<<"                S      SSSSS                      "<<endl;
cout<<"                SSS     SSSS                      "<<endl;
cout<<"                   SSSSSS                         "<<endl;
cout<<"                                            "<<endl;
cout<<"                                            "<<endl;
cout<<"               UUUUU    UUUU                     "<<endl;
cout<<"                UUU      UU                      "<<endl;
cout<<"                UUU      UU                      "<<endl;
cout<<"                UUU      UU                      "<<endl;
cout<<"                UUU      UU                       "<<endl;
cout<<"                UUU      UU                       "<<endl;
cout<<"                 UUU    UU                        "<<endl;
cout<<"                  UUUUUUU                         "<<endl;
cout<<"                                            "<<endl;
}